export const states = {
  AN: "Andaman and Nicobar Islands",
  AP: "Andhra Pradesh",
  AR: "Arunachal Pradesh",
  AS: "Assam",
  BR: "Bihar",
  CG: "Chandigarh",
  CH: "Chhattisgarh",
  DN: "Dadra and Nagar Haveli",
  DD: "Daman and Diu",
  DL: "Delhi",
  GA: "Goa",
  GJ: "Gujarat",
  HR: "Haryana",
  HP: "Himachal Pradesh",
  JK: "Jammu and Kashmir",
  JH: "Jharkhand",
  KA: "Karnataka",
  KL: "Kerala",
  LA: "Ladakh",
  LD: "Lakshadweep",
  MP: "Madhya Pradesh",
  MH: "Maharashtra",
  MN: "Manipur",
  ML: "Meghalaya",
  MZ: "Mizoram",
  NL: "Nagaland",
  OR: "Odisha",
  PY: "Puducherry",
  PB: "Punjab",
  RJ: "Rajasthan",
  SK: "Sikkim",
  TN: "Tamil Nadu",
  TS: "Telangana",
  TR: "Tripura",
  UP: "Uttar Pradesh",
  UK: "Uttarakhand",
  WB: "West Bengal",
};

export const constituency = [
  {
    name: "Belgaum",
    reserved: "None",
    constituencyCode: "C1",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    id: "C1",
  },
  {
    name: "Bagalkot",
    reserved: "SC",
    constituencyCode: "C2",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    id: "C2",
  },
  {
    name: "Bidar",
    reserved: "None",
    constituencyCode: "C3",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    id: "C3",
  },
  {
    name: "Koppal",
    reserved: "None",
    constituencyCode: "C4",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    id: "C4",
  },
  {
    name: "Haveri",
    reserved: "None",
    constituencyCode: "C5",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    id: "C5",
  },
];
export const voters = [
  {
    name: "Suresh A",
    aadharNumber: "4909-0261-4657",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C1",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "2A",
    id: "V1",
  },
  {
    name: "Vindo MR",
    aadharNumber: "4909-0261-4658",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C2",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "3A",
    id: "V2",
  },
  {
    name: "Karnad KM",
    aadharNumber: "4909-0261-4656",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C3",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "SC",
    id: "V3",
  },
  {
    name: "Pratik",
    aadharNumber: "4909-0261-4656",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C4",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "ST",
    id: "V4",
  },
  {
    name: "Kumar Sanket",
    aadharNumber: "4909-0261-4655",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C5",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "SC",
    id: "V5",
  },
  {
    name: "Kunal Kumar",
    aadharNumber: "4909-0261-4654",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C1",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "1C",
    id: "V6",
  },
  {
    name: "Pushkar Kumar",
    aadharNumber: "4909-0261-4653",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C2",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "1D",
    id: "V7",
  },
  {
    name: "Narendra",
    aadharNumber: "4909-0261-4652",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C3",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "ST",
    id: "V8",
  },
  {
    name: "Raghu",
    aadharNumber: "4909-0261-4651",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C4",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "2B",
    id: "V9",
  },
  {
    name: "Michel MK",
    aadharNumber: "4909-0261-4650",
    age: "23",
    dob: "27-11-1999",
    constituencyCode: "C5",
    address: "#36 1st cross",
    city: "Benaluru",
    state: states.KA,
    stateCode: "KA",
    country: "India",
    isAlive: true,
    caste: "3B",
    id: "V10",
  },

  {
    name: "Narendra Modi",
    aadharNumber: "4909-0261-4617",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C1",
    city: "Bengaluru",
    caste: "1A",
    id: "V11",
  },
  {
    name: "Rahul Gandhi",
    aadharNumber: "4909-0261-4627",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C1",
    city: "Bengaluru",
    caste: "2A",
    id: "V12",
  },
  {
    name: "Tejaswi Yadav",
    aadharNumber: "4909-0261-4637",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C2",
    city: "Bengaluru",
    caste: "3C",
    id: "V13",
  },
  {
    name: "Arvind Kejriwal",
    aadharNumber: "4909-0261-4647",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C2",
    city: "Bengaluru",
    caste: "3B",
    id: "V14",
  },
  {
    name: "Jyoti Basu",
    aadharNumber: "4909-0261-4657",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C3",
    city: "Bengaluru",
    caste: "3A",
    id: "V15",
  },
  {
    name: "Amit Shah",
    aadharNumber: "4909-0261-4667",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C3",
    city: "Bengaluru",
    caste: "3A",
    id: "V16",
  },
  {
    name: "Priyanka Gandhi",
    aadharNumber: "4909-0261-4677",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C4",
    city: "Bengaluru",
    caste: "2B",
    id: "V17",
  },
  {
    name: "Lalu Yadav",
    aadharNumber: "4909-0261-4687",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C4",
    city: "Bengaluru",
    caste: "SC",
    id: "V18",
  },
  {
    name: "Manish Sisodia",
    aadharNumber: "4909-0261-4697",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C5",
    city: "Bengaluru",
    caste: "ST",
    id: "V19",
  },
  {
    name: "Prakash Karat",
    aadharNumber: "4909-0261-4557",
    age: "23",
    dob: "27-11-1999",
    address: "#36 1st cross",
    country: "India",
    isAlive: true,
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C5",
    city: "Bengaluru",
    caste: "3A",
    id: "V20",
  },
];

export const parties = [
  {
    id: "P1",
    name: "Bharatiya Janata Party",
    estDate: "15-08-1947",
    memebersCount: 100000,
    partyShortcut: "BJP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/bjp_nk4snw.png",
  },
  {
    id: "P2",
    name: "Indian National Congress",
    estDate: "15-08-1947",
    memebersCount: 100000,
    partyShortcut: "INC",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/inc_s1oqn5.png",
  },
  {
    id: "P3",
    name: "Rashtriya Janata Dal",
    estDate: "15-08-1947",
    memebersCount: 100000,
    partyShortcut: "RJD",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/1200px-RJD_Flag.svg_arrrvt.png",
  },
  {
    id: "P4",
    name: "Communist Party of India (Marxist)",
    estDate: "15-08-1947",
    memebersCount: 100000,
    partyShortcut: "CPIM",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/1024px-Cpim_party_symbol.svg_mu1gpp.png",
  },
  {
    id: "P5",
    name: "Aam Aadmi Party",
    estDate: "15-08-1947",
    memebersCount: 100000,
    partyShortcut: "AAP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/aap_ujguyl.png",
  },
];

export const candidates = [
  {
    name: "Narendra Modi",
    aadharNumber: "4909-0261-4617",
    partyShortcut: "BJP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/bjp_nk4snw.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C1",
    caste: "1A",
    id: "CD1",
    voterId: "V11",
  },
  {
    name: "Rahul Gandhi",
    aadharNumber: "4909-0261-4627",
    partyShortcut: "INC",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/inc_s1oqn5.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C1",
    caste: "2A",
    id: "CD2",
    voterId: "V12",
  },
  {
    name: "Tejaswi Yadav",
    aadharNumber: "4909-0261-4637",
    partyShortcut: "RJD",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/1200px-RJD_Flag.svg_arrrvt.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C2",
    caste: "3C",
    id: "CD3",
    voterId: "V13",
  },
  {
    name: "Arvind Kejriwal",
    aadharNumber: "4909-0261-4647",
    partyShortcut: "AAP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/aap_ujguyl.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C2",
    caste: "3B",
    id: "CD4",
    voterId: "V14",
  },
  {
    name: "Jyoti Basu",
    aadharNumber: "4909-0261-4657",
    partyShortcut: "CPIM",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/1024px-Cpim_party_symbol.svg_mu1gpp.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C3",
    caste: "3A",
    id: "CD5",
    voterId: "V15",
  },
  {
    name: "Amit Shah",
    aadharNumber: "4909-0261-4667",
    partyShortcut: "BJP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/bjp_nk4snw.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C3",
    caste: "3A",
    id: "CD6",
    voterId: "V16",
  },
  {
    name: "Priyanka Gandhi",
    aadharNumber: "4909-0261-4677",
    partyShortcut: "INC",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/inc_s1oqn5.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C4",
    caste: "2B",
    id: "CD7",
    voterId: "V17",
  },
  {
    name: "Lalu Yadav",
    aadharNumber: "4909-0261-4687",
    partyShortcut: "RJD",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/1200px-RJD_Flag.svg_arrrvt.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C4",
    caste: "SC",
    id: "CD8",
    voterId: "V18",
  },
  {
    name: "Manish Sisodia",
    aadharNumber: "4909-0261-4697",
    partyShortcut: "AAP",
    partyFlag: "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101065/aap_ujguyl.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C5",
    caste: "ST",
    id: "CD9",
    voterId: "V19",
  },
  {
    name: "Prakash Karat",
    aadharNumber: "4909-0261-4557",
    partyShortcut: "CPIM",
    partyFlag:
      "https://res.cloudinary.com/dj9ttsbgm/image/upload/v1648101064/1024px-Cpim_party_symbol.svg_mu1gpp.png",
    stateCode: "KA",
    state: states.KA,
    constituencyCode: "C5",
    caste: "3A",
    id: "CD10",
    voterId: "V20",
  },
];
export const votes = [
  {
    voterId: "V1",
    candidateId: "CD1",
    constituencyCode: "C1",
    stateCode: "KA",
    partyShortcut: "BJP",
  },
  {
    voterId: "V6",
    candidateId: "CD2",
    constituencyCode: "C1",
    stateCode: "KA",
    partyShortcut: "INC",
  },
  {
    voterId: "V11",
    candidateId: "CD2",
    constituencyCode: "C1",
    stateCode: "KA",
    partyShortcut: "INC",
  },
  {
    voterId: "V16",
    candidateId: "CD2",
    constituencyCode: "C1",
    stateCode: "KA",
    partyShortcut: "INC",
  },

  {
    voterId: "V2",
    candidateId: "CD3",
    constituencyCode: "C2",
    stateCode: "KA",
    partyShortcut: "RJD",
  },
  {
    voterId: "V7",
    candidateId: "CD3",
    constituencyCode: "C2",
    stateCode: "KA",
    partyShortcut: "RJD",
  },
  {
    voterId: "V12",
    candidateId: "CD4",
    constituencyCode: "C2",
    stateCode: "KA",
    partyShortcut: "AAP",
  },
  {
    voterId: "V17",
    candidateId: "CD4",
    constituencyCode: "C2",
    stateCode: "KA",
    partyShortcut: "AAP",
  },

  {
    voterId: "V3",
    candidateId: "CD5",
    constituencyCode: "C3",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },
  {
    voterId: "V8",
    candidateId: "CD5",
    constituencyCode: "C3",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },
  {
    voterId: "V13",
    candidateId: "CD5",
    constituencyCode: "C3",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },
  {
    voterId: "V18",
    candidateId: "CD5",
    constituencyCode: "C3",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },

  {
    voterId: "V4",
    candidateId: "CD8",
    constituencyCode: "C4",
    stateCode: "KA",
    partyShortcut: "RJD",
  },
  {
    voterId: "V9",
    candidateId: "CD8",
    constituencyCode: "C4",
    stateCode: "KA",
    partyShortcut: "RJD",
  },
  {
    voterId: "V14",
    candidateId: "CD8",
    constituencyCode: "C4",
    stateCode: "KA",
    partyShortcut: "RJD",
  },
  {
    voterId: "V19",
    candidateId: "CD7",
    constituencyCode: "C4",
    stateCode: "KA",
    partyShortcut: "INC",
  },

  {
    voterId: "V5",
    candidateId: "CD10",
    constituencyCode: "C5",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },
  {
    voterId: "V10",
    candidateId: "CD10",
    constituencyCode: "C5",
    stateCode: "KA",
    partyShortcut: "CPIM",
  },
  {
    voterId: "V15",
    candidateId: "CD9",
    constituencyCode: "C5",
    stateCode: "KA",
    partyShortcut: "AAP",
  },
  {
    voterId: "V20",
    candidateId: "CD9",
    constituencyCode: "C5",
    stateCode: "KA",
    partyShortcut: "AAP",
  },
];
