# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

volumes:
  orderer.election_commission:
  orderer2.election_commission:
  orderer3.election_commission:
  peer0.my_party:
  peer0.election_commission:

networks:
  test:
    name: fabric_test

services:

  orderer.election_commission:
    container_name: orderer.election_commission
    image: hyperledger/fabric-orderer:2.2.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ElectionCommissionMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.election_commission:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../ca/organizations/election_commission/orderers/orderer.election_commission/msp:/var/hyperledger/orderer/msp
        - ../ca/organizations/election_commission/orderers/orderer.election_commission/tls/:/var/hyperledger/orderer/tls
        - orderer.election_commission:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 9443:9443
    networks:
      - test


  orderer2.election_commission:
    container_name: orderer2.election_commission
    image: hyperledger/fabric-orderer:2.2.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ElectionCommissionMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer2.election_commission:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../ca/organizations/election_commission/orderers/orderer2.election_commission/msp:/var/hyperledger/orderer/msp
        - ../ca/organizations/election_commission/orderers/orderer2.election_commission/tls/:/var/hyperledger/orderer/tls
        - orderer2.election_commission:/var/hyperledger/production/orderer
    ports:
      - 8050:8050
      - 9453:9443
    networks:
      - test



  orderer3.election_commission:
    container_name: orderer3.election_commission
    image: hyperledger/fabric-orderer:2.2.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ElectionCommissionMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer3.election_commission:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../ca/organizations/election_commission/orderers/orderer3.election_commission/msp:/var/hyperledger/orderer/msp
        - ../ca/organizations/election_commission/orderers/orderer3.election_commission/tls/:/var/hyperledger/orderer/tls
        - orderer3.election_commission:/var/hyperledger/production/orderer
    ports:
      - 9050:9050
      - 9543:9443
    networks:
      - test

  peer0.my_party:
    container_name: peer0.my_party
    image: hyperledger/fabric-peer:2.2.9
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.my_party
      - CORE_PEER_ADDRESS=peer0.my_party:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.my_party:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.my_party:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.my_party:7051
      - CORE_PEER_LOCALMSPID=MyPartyMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.my_party:9444
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../ca/organizations/my_party/peers/peer0.my_party/msp:/etc/hyperledger/fabric/msp
        - ../ca/organizations/my_party/peers/peer0.my_party/tls:/etc/hyperledger/fabric/tls
        - peer0.my_party:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    networks:
      - test


  peer0.election_commission:
      container_name: peer0.election_commission
      image: hyperledger/fabric-peer:2.2.9
      environment:
        #Generic peer variables
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
        - FABRIC_LOGGING_SPEC=INFO
        #- FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        # Peer specific variabes
        - CORE_PEER_ID=peer0.election_commission
        - CORE_PEER_ADDRESS=peer0.election_commission:8051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
        - CORE_PEER_CHAINCODEADDRESS=peer0.election_commission:10052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.election_commission:8051
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.election_commission:8051
        - CORE_PEER_LOCALMSPID=ElectionCommissionMSP
        - CORE_OPERATIONS_LISTENADDRESS=peer0.election_commission:9446
      volumes:
          - /var/run/docker.sock:/host/var/run/docker.sock
          - ../ca/organizations/election_commission/peers/peer0.election_commission/msp:/etc/hyperledger/fabric/msp
          - ../ca/organizations/election_commission/peers/peer0.election_commission/tls:/etc/hyperledger/fabric/tls
          - peer0.election_commission:/var/hyperledger/production
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: peer node start
      ports:
        - 8051:8051
        - 9446:9446
      networks:
        - test

