export default {
    ELECTION_COMMISSION: "ELECTION_COMMISSION",
    VOTE: "VOTE",
    PARTY: "PARTY",
    VOTER_ID:"VOTER_ID",
    CONSTITUENCY: "CONSTITUENCY",
    ELECTION_COMMISSION_MSP:"ELECTION_COMMISSION_MSP",
    CANDIDATE:"CANDIDATE",
    ELECTION_COMMISSION_CHIEF: "ELECTION_COMMISSION_CHIEF",
    ELECTION_TIMESTAMP: "ELECTION_TIMESTAMP",
    ELECTION:"ELECTION",
    BALLOT: "BALLOT",
}