    export const errors = {
    "CONSTITUENCY_ALREADY_EXIST": "CONSTITUENCY_ALREADY_EXIST",
    "MISSING_CHAINCODE_ARGUMENTS": "MISSING_CHAINCODE_ARGUMENTS",
    "NO_RECORD_FOUND": "NO_RECORD_FOUND",
    "INVOKING_USER_NOT_REGISTERED": "INVOKING_USER_NOT_REGISTERED",
    "NOT_AUTHORIZED": "NOT_AUTHORIZED",
    "CHAINCODE_ERROR": "CHAINCODE_ERROR",
    "PARTY_ALREADY_EXIST": "PARTY_ALREADY_EXIST",
    "CONSTITUENCY_NOT_EXIST": "CONSTITUENCY_NOT_EXIST",
    "VOTERID_ALREADY_EXIST":"VOTERID_ALREADY_EXIST",
    "CANDIDATE_ALREADY_EXIST":"CANDIDATE_ALREADY_EXIST",
    "VOTERID_NOT_EXIST": "VOTERID_NOT_EXIST",
    "CANDIDATE_NOT_EXIST":"CANDIDATE_NOT_EXIST"
}